// Code generated by hertz generator. DO NOT EDIT.

package router_gen

import (
	pingpong_api "pingpong_server/api/router_gen/pingpong/api"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	pingpong_api.Register(r)
}
