// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	pingpong_console "console.pingpong.ai/router_gen/pingpong/console"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	pingpong_console.Register(r)
}
