// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"

	"pingpong_server/api/middleware"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.ClientInfoMiddleware()}
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _agentsMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.AuthMiddleware()}
}

func _getmyitemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginstartMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginverifyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _itemsMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.AuthMiddleware()}
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchfeedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _websiteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlatestitemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getwebsitestatsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pmMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.AuthMiddleware()}
}

func _listconnectorsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fetchpmMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendpmMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listconversationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconvhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _closeconvMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemyitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _items0Mw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.AuthMiddleware()}
}

func _listfriendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _blockuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handlefriendrequestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendfriendrequestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfriendrequestsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unblockuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unfriendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationsMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.AuthMiddleware()}
}

func _updatefriendremarkMw() []app.HandlerFunc {
	// your code...
	return nil
}
