// Code generated by hertz generator.

// @title           pingpong_server Console API
// @version         1.0
// @description     PingPong Console API for querying and managing agents and items
// @host            localhost:8090
// @BasePath        /

package main

import (
	"context"
	"log"
	"os"
	"strings"

	consoleHandler "console.pingpong.ai/handler_gen/pingpong/console"
	_ "console.pingpong.ai/docs"
	"console.pingpong.ai/internal/config"
	"console.pingpong.ai/internal/db"
	"console.pingpong.ai/internal/idgen"
	"console.pingpong.ai/internal/logger"
	"console.pingpong.ai/internal/notification"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	hertzSwagger "github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
)

func main() {
	cfg := config.Load()
	logger.Init("console/console_api/.log")

	db.InitPostgres(cfg.PgDSN)
	log.Println("PostgreSQL connected")

	db.InitRedis(cfg.RedisAddr, cfg.RedisPassword)
	log.Println("Redis connected")

	etcdEndpoints := config.EtcdEndpoints(cfg.EtcdAddr)
	notifIDGen, err := idgen.NewManagedGenerator(context.Background(), idgen.ManagedGeneratorConfig{
		Endpoints:      etcdEndpoints,
		WorkerPrefix:   cfg.IDWorkerPrefix,
		ServiceName:    "console-notif-id",
		InstanceID:     cfg.IDInstanceID,
		LeaseTTLSecond: cfg.IDWorkerLeaseTTL,
		EpochMS:        cfg.IDSnowflakeEpoch,
	})
	if err != nil {
		log.Fatalf("failed to init notification id generator: %v", err)
	}
	defer func() { _ = notifIDGen.Close(context.Background()) }()
	consoleHandler.InitNotificationService(notifIDGen)

	notifSvc := notification.NewService(db.DB, db.RDB)
	if recoverErr := notifSvc.RecoverActiveNotifications(context.Background()); recoverErr != nil {
		log.Printf("[console] Warning: failed to recover active notifications: %v", recoverErr)
	}

	h := server.Default(server.WithHostPorts(cfg.ListenAddr()))

	allowOrigins := parseAllowOrigins()
	h.Use(cors.New(cors.Config{
		AllowOrigins:     allowOrigins,
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Accept"},
		AllowCredentials: false,
	}))

	h.GET("/swagger/*any", hertzSwagger.WrapHandler(swaggerFiles.Handler))

	register(h)

	log.Printf("Console API gateway starting on %s", cfg.ListenAddr())
	h.Spin()
}

func parseAllowOrigins() []string {
	raw := strings.TrimSpace(os.Getenv("CONSOLE_CORS_ALLOW_ORIGINS"))
	if raw == "" {
		return []string{"*"}
	}
	parts := strings.Split(raw, ",")
	origins := make([]string, 0, len(parts))
	for _, part := range parts {
		origin := strings.TrimSpace(part)
		if origin != "" {
			origins = append(origins, origin)
		}
	}
	if len(origins) == 0 {
		return []string{"*"}
	}
	return origins
}
